const clientes = [
    {
        id: 1,
        nombre:"Unila Primera",
        comuna:"Ñuñoa",
        producto:"Lentes Ópticos",
        fechaVenta: new Date(2024,1,1),
        precio: 11000,
    },
    {
        id: 2,
        nombre:"Else Gundo",
        comuna:"Cachiyuyo",
        producto:"Lentes de Descanso",
        fechaVenta: new Date(2024,2,2),
        precio: 22000,
    },
    {
        id: 3,
        nombre:"Tres Tristes Tigres",
        comuna:"Osorno",
        producto:"Lentes de Sol",
        fechaVenta: new Date(2024,3,3),
        precio: 33000,
    },
    {
        id: 4,
        nombre:"Cua Troncoso",
        comuna:"Valparaiso",
        producto:"Lentes Ópticos de Sol",
        fechaVenta: new Date(2024,4,4),
        precio: 44000,
    },
    {
        id: 5,
        nombre:"LeeSin Contreras",
        comuna:"Quinta Normal",
        producto:"Cambio de Cristales",
        fechaVenta: new Date(2024,5,5),
        precio: 55000,
    },
    {
        id: 6,
        nombre:"Camilo Sexto",
        comuna:"Coquimbo",
        producto:"Sólo Armazón",
        fechaVenta: new Date(2024,6,6),
        precio: 66000,
    },
    {
        id: 7,
        nombre:"Sie Tenchi",
        comuna:"Puente Alto",
        producto:"Lentes de Descanso",
        fechaVenta: new Date(2024,7,7),
        precio: 77000,
    },
    {
        id: 8,
        nombre:"Osho Gurú",
        comuna:"Oshorno",
        producto:"Lentes de Sol",
        fechaVenta: new Date(2024,8,8),
        precio: 88000,
    },
    {
        id: 9,
        nombre:"Nine Tales",
        comuna:"Arica",
        producto:"Lentes de Sol",
        fechaVenta: new Date(2024,9,9),
        precio: 90000,
    },
    {
        id: 10,
        nombre:"Jony Melavo",
        comuna:"Arica",
        producto:"Lentes Ópticos",
        fechaVenta: new Date(2024,10,10),
        precio: 10000,
    },
    {
        id: 11,
        nombre:"Jony Melavo",
        comuna:"Valparaiso",
        producto:"Lentes Ópticos de Sol",
        fechaVenta: new Date(2024,11,11),
        precio: 110000,
    },
    {
        id: 12,
        nombre:"Cindi Ciembre",
        comuna:"Santiago",
        producto:"Lentes Ópticos de Sol",
        fechaVenta: new Date(2024,12,12),
        precio: 120000,
    },
]